config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#index'

  post '/posts/load', to: 'posts#load'
  resources :posts, only: %i[create index], shallow: true do
    resources :likes, only: %i[create]
  end

  post '/ranking/load', to: 'ranking#load'
  resources :ranking, only: %i[index show edit update destroy]

  if Rails.env.development?
    require 'sidekiq/web'
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :user_id, uniqueness: { scope: :post, message: 'は同じコメントにいいね出来ません' }
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  has_many :likes, dependent: :destroy
  belongs_to :user

  validates :message, length: { maximum: 50 }, presence: true

  # いいねをlike_countとして含めた上で、like_countの降順で投稿一覧を取得する
  scope :desc_likes_count, lambda {
    select('posts.*, COALESCE(COUNT, 0) AS like_count')
      .joins(
        <<~JOIN
          LEFT JOIN (
            SELECT
              post_id, COUNT(*)
            FROM
              likes
            GROUP BY post_id
          ) AS likes_table
          ON
            posts.id = likes_table.post_id
        JOIN
      )
      .order(like_count: :desc, created_at: :desc)
  }
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :posts, dependent: :nullify
  has_many :likes, dependent: :nullify

  attribute :name, :string, default: "ぼっち #{Gimei.first}"

  validates :name, presence: true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include ApplicationHelper
  include FlashHelper

  before_action :have_current_user

  def have_current_user
    unless current_user
      flash[:alert] = 'なんかエラーおきました(^_^;)ｻｰｾﾝ'
      redirect_to root_url
    end
  end

  def turbo_stream_flash
    turbo_stream.replace('flash_bar', partial: 'layouts/flash', locals: { **flash_attributes })
  end

  # @param [ActiveRecord]
  def turbo_stream_error_messages(object)
    turbo_stream.replace('error_messages', partial: 'shared/error_messages', object:)
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  skip_before_action :have_current_user

  def index; end
end

app/controllers/likes_controller.rb
# frozen_string_literal: true

class LikesController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @post.likes.create!(user_id: current_user.id)
    turbo_stream
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  skip_before_action :have_current_user, only: :index

  def index
    unless current_user
      @current_user = User.create!
      session[:user_id] = @current_user.id
    end

    Turbo::StreamsChannel.broadcast_replace_to('tweet_page',
                                               target: 'login_announce',
                                               partial: 'posts/login_announce',
                                               locals: { user: current_user, me: false })
    @posts = Post.desc_likes_count.includes(:likes).page(1)
  end

  def create
    post = current_user.posts.build(post_params)

    if post.save
      ChaplusApiJob.perform_later(current_user, post)
      render turbo_stream:
               turbo_stream.replace('bot_message',
                                    partial: 'chaplus_api/message',
                                    locals: { bot_message: t("bot.loading") })
    else
      render turbo_stream:
               turbo_stream_error_messages(post),
             status: :unprocessable_entity
    end
  end

  def load
    @posts = Post.desc_likes_count.includes(:likes).page(params[:page])
    turbo_stream
  end

  private

  def post_params
    params.require(:post).permit(:message, :user_id, :bot_message)
  end
end

app/controllers/ranking_controller.rb
class RankingController < ApplicationController

  def index
    @posts = Post.desc_likes_count.includes(:user, :likes).page(1).per(20)
  end

  def show
    post = Post.find(params[:id])
    render partial: 'ranking/post_message', locals: { post: }
  end

  def edit
    post = Post.find(params[:id])
    render partial: 'ranking/edit', locals: { post: }
  end

  def update
    post = current_user.posts.find(params[:id])
    if post.update(post_params)
      flash.now[:notice] = t("default.message.updated", item: Post.model_name.human)
      render turbo_stream: [
        turbo_stream.replace(helpers.dom_id(post, :message), partial: 'ranking/post_message', locals: { post: }),
        turbo_stream_flash
      ]
    else
      flash.now[:alert] = t("default.message.not_updated", item: Post.model_name.human)
      render turbo_stream: [turbo_stream_flash, turbo_stream_error_messages(post)], status: :unprocessable_entity
    end
  end

  def destroy
    post = current_user.posts.find(params[:id])
    post.destroy!
    flash.now[:notice] = t("default.message.destroyed", item: Post.model_name.human)
    render turbo_stream: [turbo_stream.remove(post), turbo_stream_flash]
  end

  def load
    @posts = Post.desc_likes_count.includes(:user, :likes).page(params[:page]).per(20)
    turbo_stream
  end

  private

  def post_params
    params.require(:post).permit(:message)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  # @return [User]
  def current_user
    id = session[:user_id]
    @current_user ||= User.find_by(id:) if id
  end

  # @return [Integer]
  # 現在のコネクション数から自分を除いた数を返す
  # コネクション接続のタイミング上、初回の接続は自分を含めることができず-1になってしまう可能性があるため、
  # 計算結果がマイナスなら0を返す処理を入れている。
  def current_connection_length
    return_length = ActionCable.server.open_connections_statistics.length - 1
    return_length.negative? ? 0 : return_length
  end
end

app/helpers/flash_helper.rb
# frozen_string_literal: true

module FlashHelper
  FLASH_ICON_PATH = {
    NOTICE: 'M20 3.33331C10.8 3.33331 3.33337 10.8 3.33337 20C3.33337 29.2 10.8 36.6666 20 36.6666C29.2 36.6666 36.6667
              29.2 36.6667 20C36.6667 10.8 29.2 3.33331 20 3.33331ZM16.6667 28.3333L8.33337 20L10.6834 17.65L16.6667
              23.6166L29.3167 10.9666L31.6667 13.3333L16.6667 28.3333Z',
    ALERT: 'M20 3.36667C10.8167 3.36667 3.3667 10.8167 3.3667 20C3.3667 29.1833 10.8167 36.6333 20 36.6333C29.1834 36.6333 36.6334 29.1833 36.6334 20C36.6334 10.8167 29.1834 3.36667 20 3.36667ZM19.1334 33.3333V22.9H13.3334L21.6667 6.66667V17.1H27.25L19.1334 33.3333Z'
  }.freeze

  # flashのタイプに応じたハッシュを返す。
  # { bg: String, text: String, title: String, message: String, path: String }
  def flash_attributes
    case flash.keys
    in ['notice']
      { bg: 'bg-emerald-500', text: 'text-emerald-500', title: 'Success', message: flash.notice,
        path: FLASH_ICON_PATH[:NOTICE] }
    in ['alert']
      { bg: 'bg-red-500', text: 'text-red-500', title: 'Error', message: flash.alert, path: FLASH_ICON_PATH[:ALERT] }
    else
      { bg: '', text: '', title: '', message: '', path: '' }
    end
  end
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def default_meta_tags
    {
      site: 'ぼっちなう',
      title: '新感覚リアルタイムSNS「ぼっちなう」',
      reverse: true,
      charset: 'utf-8',
      description: '会話BOTとのおしゃべりがリアルタイムに共有できる!「緩いつながり」を感じることのできる新感覚SNS!',
      keywords: '会話BOT,Rails7,HotWire,rails-turbo',
      canonical: request.original_url,
      separator: '|',
      icon: [
        { href: image_url('logo.png'), rel: 'apple-touch-icon', sizes: '180x180', type: 'image/png' },
      ],
      og: {
        site_name: 'ぼっちなう',
        title: 'ぼっちなう',
        description: '会話BOTとのおしゃべりがリアルタイムに共有できる!「緩いつながり」を感じることのできる新感覚SNS!',
        type: 'website',
        url: request.original_url,
        image: image_url('ogp.png'),
        locale: 'ja_JP',
      },
      twitter: {
        card: 'summary',
        site: '@6MvpqmS7ThQbuBc',
      }
    }
  end
end

app/views/chaplus_api/_message.html.slim
#bot_message.flex.items-center
  = bot_message
  - if bot_message == t("bot.loading")
    svg.animate-spin.-ml-1.mr-3.h-5.w-5.text-sky-400 fill="none" viewbox=("0 0 24 24") xmlns="http://www.w3.org/2000/svg"
      circle.opacity-25 cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"
      path.opacity-75 d=("M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z") fill="currentColor"
  - else
    span.relative.inline-flex.rounded-full.h-3.w-3.bg-sky-500.justify-center.items-center.ml-1
      span.animate-ping.absolute.inline-flex.w-4.h-4.rounded-full.bg-sky-400.opacity-75

app/views/home/index.html.slim
.p-8.text-gray-500.bg-white.shadow-md.border.border-gray-100.rounded-2xl.font-medium.absolute.bottom-28.sm:bottom-40.border-4.border-amber-800
  h1.text-lg.sm:text-xl.text-center.mb-4.text-black ひとりぼっちでも大丈夫！会話BOTと会話して孤独を紛らわそう！！
  ol.list-decimal.text-sm.sm:text-base
    li.mb-2 自由につぶやいてみましょう。会話BOTが返事をしてくれます。
    li.mb-2 他の人の会話BOTとのやりとりを見ることができます。面白いと思ったやりとりにはクリックしていいねしましょう。
    li.mb-2 会話はリアルタイムに送信されます。"NOW!"と書かれたつぶやきは現在送信されたものなので、記念にいいねしときましょう。
    li ランキングでいいね数を見ることができます。自分のつぶやきが上位に来るといいですね。

= link_to 'つぶやく', posts_path, class: "btn-primary h-16 w-2/6 md:w-1/6 absolute bottom-5 sm:bottom-20 inset-x-1/2 -translate-x-1/2"

app/views/layouts/_background.html.slim
= image_tag('top-bg.jpg', class: 'h-screen w-screen absolute z-0 object-cover object-right-bottom')
- if current_page?(root_path)
  = image_tag('logo.png', class: 'absolute inset-x-1/2 -translate-x-1/2 h-2/5 drop-shadow-2xl animate-[slide-in_1s]')

css:
  @keyframes slide-in {
      0% {
          opacity: 0;
          transform: translate(-50%, 30px);
      }
      100% {
          opacity: 1;
          transform: translate(-50%, 0px);
      }
  }

app/views/layouts/_flash.html.slim
div[id="flash_bar"
    class="flex w-full max-w-sm mx-auto overflow-hidden bg-white rounded-lg shadow-lg dark:bg-gray-800 absolute top-20 opacity-0 transition-opacity"
    data-controller="flash" data-flash-has-flash-value="#{flash.present?}"]

  div class="flex items-center justify-center w-12 #{bg}"
    svg.w-6.h-6.text-white.fill-current viewbox=("0 0 40 40") xmlns="http://www.w3.org/2000/svg"
      path d=(path)

  .px-4.py-2.-mx-3
    .mx-3
      span class="font-semibold #{text}" = title
      p.text-sm.text-gray-600.dark:text-gray-200 = message

app/views/layouts/application.html.slim
doctype html
html
head
= display_meta_tags(default_meta_tags)
meta[name="viewport" content="width=device-width,initial-scale=1"]
= csrf_meta_tags
= csp_meta_tag
= stylesheet_link_tag "application", "data-turbo-track": "reload"
= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload"
= javascript_importmap_tags

body
= render 'layouts/background'

main class="h-screen container mx-auto relative z-10 flex justify-center"
  = render partial: 'layouts/flash', locals: { **flash_attributes }
  = yield

app/views/likes/_like_button.html.slim
div id=dom_id(post, :like) class='flex justify-between items-end text-xs sm:text-sm'
  = "いいね！#{post.likes.length}"

  .row-start-3.col-start-3.inline-block
    - if post.current_user_liked?(user)
      .like-btn-base.text-white.bg-pink-500.w-6.sm:w-8.h-6.sm:h-8
        svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"
          path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7"

    - else
      = button_to post_likes_path(post), \
                  disabled: true, \
                  class: 'like-btn-base text-white bg-green-600 cursor-pointer w-6 sm:w-8 h-6 sm:h-8' do
        svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"
          path[stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
            d="M14 10h4.764a2 2 0 011.789 2.894l-3.5 7A2 2 0 0115.263 21h-4.017c-.163 0-.326-.02-.485-.06L7 20m7-10V5a2 2 \
                    0 00-2-2h-.095c-.5 0-.905.405-.905.905 0 .714-.211 1.412-.608 2.006L7 11v9m7-10h-2M7 20H5a2 2 0 01-2-2v-6a2 2 0 012-2h2.5"]

app/views/likes/create.turbo_stream.slim
- if request.referer.include?('/posts')
  = turbo_stream.replace( dom_id(@post, :like), \
                          partial: 'likes/like_button',  \
                          locals: { post: @post, user: current_user })

- elsif request.referer.include?('/ranking')
  = turbo_stream.replace( dom_id(@post, :ranking_good_btn), \
                          partial: 'ranking/good_btn', \
                          locals: { post: @post, user: current_user })

app/views/posts/_like_button.html.slim
.row-start-3.col-start-3.inline-block
  = button_to  post, \
               params: { post: { like: post.like.to_i + 1 } }, \
               form: { data: { action: 'turbo:submit-end->posts#disableLikeButton' } },
               class: %w[inline-flex items-center justify-center space-x-2 border border-transparent text-sm font-medium \
                         rounded-full w-12 h-12 text-white bg-green-600 hover:bg-green-700 transition-colors] do
    svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor"
      path[stroke-linecap="round"
           stroke-linejoin="round"
           stroke-width="2"
           d="M14 10h4.764a2 2 0 011.789 2.894l-3.5 7A2 2 0 0115.263 21h-4.017c-.163 0-.326-.02-.485-.06L7 20m7-10V5a2 2 \
            0 00-2-2h-.095c-.5 0-.905.405-.905.905 0 .714-.211 1.412-.608 2.006L7 11v9m7-10h-2M7 20H5a2 2 0 01-2-2v-6a2 2 0 012-2h2.5"]

app/views/posts/_login_announce.html.slim
#login_announce
  inline-block.rounded-full.bg-white.pr-5.h-16.fixed.top-40.left-20.opacity-0.shadow-md.border-2.border-gray-700 style="line-height: 3.75rem; animation: login_announce 7s"
    img.rounded-full.float-left.h-full.bg-gray-50 src="https://joeschmoe.io/api/v1/random" /
    span.text-xs.sm:text-sm.ml-3 = me ? "ようこそ #{user.name} さん" : "#{user.name} さんがやってきました"

  .rounded-full.py-1.px-4.font-medium.border.text-green-900.bg-green-100.border-green-300.absolute.top-20.left-0
    = "現在#{current_connection_length}人と繋がっています"

css:
  @keyframes login_announce {
      0% {
          opacity: 0;
          transform: translateX(-100px);
      }

      50% {
          opacity: 1;
          transform: translateX(0px);
      }

      100% {
          opacity: 0;
          transform: translateX(-100px);
      }
  }

app/views/posts/_post.html.slim
- post_counter ||= 0

div[id=dom_id(post)
  class="fixed top-0 bg-white sm:py-4 sm:px-16 py-2 px-8 rounded-full opacity-0 drop-shadow-xl \
          #{'hover:border-rose-600 border-2 cursor-pointer' unless post.current_user_liked?(user)}"
  data-action="animationend->paginate#postRemoveSelf"
  onpointerdown="this.querySelector('form')?.requestSubmit()"
  style="#{post.bubble_style(post_counter)} will-change: transform, opacity;"]

  - if post.now?
    p.text-xs.badge.border-2.border-pink-500.text-pink-500
      | NOW!
  - else
    p.text-xs
      = "#{time_ago_in_words(post.created_at)}前"

  p.w-28.sm:w-44.text-sm.sm:text-base.break-word style="margin-top: 0.1rem"
    = post.message

  p.text-gray-700.text-sm.sm:text-base.flex style="margin-top: 0.1rem"
    = image_tag('botti-wan.jpg', class: 'object-cover w-5 h-5 rounded-full border')
    = post.bot_message

  = render('likes/like_button', { post:, user: })

app/views/posts/index.html.slim
= turbo_stream_from 'tweet_page'
= turbo_stream_from current_user

= render partial: 'posts/login_announce', locals: { user: current_user, me: true }

div data-controller="paginate"
  #posts
    = render partial: 'posts/post', collection: @posts, locals: { user: current_user }
  span.hidden
    = render partial: 'shared/next_page', object: @posts


div id="tweet-form" class="absolute bottom-0 w-full"
  = form_with model: Post.new, \
              data: { controller: "form", \
                      action: "turbo:submit-start->form#clearErrorMessages turbo:submit-end->form#disableFewSeconds" }, \
              class: %w[w-full max-w-2xl sm:px-6 sm:py-4 mx-auto bg-white/75 rounded-md shadow-md dark:bg-gray-800] \
              do |f|

    = render partial: 'shared/error_messages', object: f.object

    = render 'chaplus_api/message', bot_message: 'こんにちは！何か質問してみんしゃい。'

    .flex
      = f.text_area :message, required: true, maxlength: 50,  class: %w[block w-full px-4 py-2 text-gray-700 \
        bg-white/75 border rounded-l-md dark:bg-gray-800 dark:text-gray-300 dark:border-gray-600 focus:border-blue-400 \
        dark:focus:border-blue-300 focus:outline-none focus:ring focus:ring-blue-300 focus:ring-opacity-40 resize-none]

      = f.submit 'つぶやく', class: %w[text-white transition-colors duration-200 transform bg-green-700 cursor-pointer \
                                    rounded-r-lg hover:bg-green-600 focus:outline-none focus:bg-green-600 block mx-auto \
                                    disabled:opacity-75 disabled:cursor-not-allowed]

= link_to 'ランキング', ranking_index_path, class: "flex justify-center px-4 py-2 absolute top-0 left-0 w-28 sm:w-32 text-sm sm:text-base btn-primary"

css:
  /* つぶやきを泡のように出現、消滅させる */
  @keyframes tweet-bubble {
      0% {
          opacity: 0;
          transform: translateY(80vh);
      }
      5% {
          opacity: 0;
      }
      80% {
          opacity: 1;
          transform: translateY(20vh);
      }
      100% {
          opacity: 0;
          transform: translateY(0px);
      }
  }

  main {
      overflow: hidden;
  }

app/views/posts/load.turbo_stream.slim
= turbo_stream.append 'posts', partial: 'posts/post', collection: @posts, locals: { user: current_user }
= turbo_stream.replace 'next_page_link', partial: 'shared/next_page', object: @posts

app/views/ranking/_edit.html.slim
= turbo_frame_tag dom_id(post, :message)
  = form_with model: post, url: ranking_path(post), method: :patch do |f|
    = render partial: 'shared/error_messages', object: post
    .flex.items-center.h-20
      = f.text_area :message, maxlength: 50, required: true, class: %w[block w-9/12 px-4 py-2 text-gray-700 \
        bg-white/75 border rounded-md dark:bg-gray-800 dark:text-gray-300 dark:border-gray-600 focus:border-blue-400 \
        dark:focus:border-blue-300 focus:outline-none focus:ring focus:ring-blue-300 focus:ring-opacity-40 resize-none]

      = f.submit '更新', class: %w[w-1/12 text-white text-sm transition-colors duration-200 transform bg-green-700 cursor-pointer \
                                  h-4/5 rounded-l-lg hover:bg-green-600 focus:outline-none focus:bg-green-600 block ml-auto]

      button type="button" class="w-1/12 text-green-900 text-sm transition-colors duration-200 transform border-2 border-green-700 \
                    h-4/5 cursor-pointer rounded-r-lg hover:bg-green-300 focus:outline-none focus:bg-green-300 block mr-auto"
        = link_to  ranking_path(post), class: 'flex h-full items-center justify-center' do
          div 戻る

app/views/ranking/_good_btn.html.slim
div.flex.sm:justify-between id= dom_id(post, :ranking_good_btn)
  = post.likes.length
  - if post.current_user_liked?(user)
    svg class="ml-3 sm:ml-0" height="24px" viewbox=("0 0 24 24") width="24px" xmlns="http://www.w3.org/2000/svg"
      path.fill-green-500 d="M9,21h9c0.83,0,1.54-0.5,1.84-1.22l3.02-7.05C22.95,12.5,23,12.26,23,12v-2c0-1.1-0.9-2-2-2h-6.31l0.95-4.57l0.03-0.32 c0-0.41-0.17-0.79-0.44-1.06L14.17,1L7.58,7.59C7.22,7.95,7,8.45,7,9v10C7,20.1,7.9,21,9,21z M9,9l4.34-4.34L12,10h9v2l-3,7H9V9z M1,9h4v12H1V9z"
  - else
    = link_to post_likes_path(post), \
                    data: { turbo_method: 'post' }, \
                    class: "hover:fill-green-500" do
      svg class="ml-3 sm:ml-0" id="ranking-good-btn" height="24px" viewbox=("0 0 24 24") width="24px" xmlns="http://www.w3.org/2000/svg"
        path d="M9,21h9c0.83,0,1.54-0.5,1.84-1.22l3.02-7.05C22.95,12.5,23,12.26,23,12v-2c0-1.1-0.9-2-2-2h-6.31l0.95-4.57l0.03-0.32 c0-0.41-0.17-0.79-0.44-1.06L14.17,1L7.58,7.59C7.22,7.95,7,8.45,7,9v10C7,20.1,7.9,21,9,21z M9,9l4.34-4.34L12,10h9v2l-3,7H9V9z M1,9h4v12H1V9z"

app/views/ranking/_post.html.slim
tr[id=dom_id(post)
  class='flex flex-col flex-nowrap mb-2 sm:table-row sm:mb-0s'
  style="width: 1000px;"
  data-paginate-target=(post_counter + 1 == @posts.limit_value ? 'infiniteScroll' : nil) ]

  td.border.hover:bg-gray-100.p-3.sm:w-1
    = post_counter + 1 + @posts.prev_page.to_i * @posts.limit_value
  td class="border hover:bg-gray-100 p-3 sm:w-2/12"
    = post.user.name
    - if post.mine?(current_user)
      span.badge.text-green-900.border-2.border-green-700
        | あなた
  td class="border hover:bg-gray-100 p-3 sm:w-4/12"
    = render 'ranking/post_message', post:
  td class="border hover:bg-gray-100 p-3 sm:w-4/12 text-ellipsis sm:text-clip whitespace-nowrap sm:whitespace-normal"
    = post.bot_message
  td class="border hover:bg-gray-100 p-3 sm:w-1/12"
    = render 'ranking/good_btn', post:, user: current_user
  td class="border hover:bg-gray-100 p-3 sm:w-1/12"
    = "#{time_ago_in_words(post.created_at)}前"

app/views/ranking/_post_message.html.slim
- if post.mine?(current_user)
  = turbo_frame_tag dom_id(post, :message) do
    = post.message
    = link_to '編集', edit_ranking_path(post), class: 'badge text-yellow-100 bg-yellow-600 hover:bg-yellow-500'
    = button_to '削除', ranking_path(post), method: :delete, class: 'badge text-red-100 bg-red-600 hover:bg-red-500', \
        form_class: 'inline-block', form: { data: { turbo_confirm: '削除してもよろしいですか？' } }
- else
  = post.message

app/views/ranking/index.html.slim
= link_to 'つぶやく', posts_path, class: "flex justify-center px-4 py-2 absolute top-0 left-0 w-24 sm:w-32 text-sm sm:text-base btn-primary"

.flex.w-full.flex-col.bg-blue-50.sm:bg-transparent data-controller="paginate"
  div.flex.justify-center
    = image_tag('ranking.png', class: 'h-40')
  table.w-full.flex.flex-row.flex-no-wrap.bg-gray-50.sm:bg-white.rounded-lg.sm:shadow-lg.my-5.sm:h-4/5
    thead.text-white.sm:block
      - @posts.total_count.times do
        tr.bg-teal-400.flex.flex-col.flex-nowrap.mb-2.sm:block.rounded-l-lg.sm:rounded-none.sm:mb-0.sm:w-full
          th.p-3.text-left.sm:inline-block.sm:w-1/12 No
          th.p-3.text-left.sm:inline-block.sm:w-2/12 名前
          th.p-3.text-left.sm:inline-block.sm:w-3/12 メッセージ
          th.p-3.text-left.sm:inline-block.sm:w-4/12 ぼっちわんからの返信
          th.p-3.text-left.sm:inline-block.sm:w-1/12 いいね
          th.p-3.text-left.sm:inline-block.sm:w-1/12 投稿日時
    tbody#ranking_tbody.flex-1.overflow-x-scroll.sm:block.sm:overflow-y-scroll.sm:overflow-x-hidden
      = render partial: 'ranking/post', collection: @posts
  .hidden
    = render partial: 'shared/next_page', object: @posts

css:
   @media (min-width: 640px) {
       table {
          display: table !important;
       }

       thead tr:not(:first-child) {
          display: none;
       }

       tbody {
           height: 90%;
       }

       main {
           background-color: transparent !important;
       }
   }

   td:last-child {
       border: 0;
   }

   th:not(:last-child) {
       border-bottom: 2px solid rgba(0, 0, 0, .1);
   }

   main {
       background-color: white;
   }

app/views/ranking/load.turbo_stream.slim
= turbo_stream.append 'ranking_tbody', partial: 'ranking/post', collection: @posts
= turbo_stream.replace 'next_page_link', partial: 'shared/next_page', object: @posts

app/views/shared/_error_messages.html.slim
#error_messages
  - if error_messages.errors.any?
    .text-red-700 data-form-target='errorMessages'
      ul.mb-0
        - error_messages.errors.full_messages.each do |message|
          li
            = message

app/views/shared/_next_page.html.slim
/ @param [ActiveRecord_Relation] object pageを付与したActiveRecord_Relationオブジェクト
= link_to_next_page next_page, \
                    'もっと見る', \
                    params: { controller: controller_name, action: 'load' }, \
                    data: { turbo_method: :post, paginate_target: :nextPageLink }, id: 'next_page_link'